config/routes.rb
Intranet::Application.routes.draw do
  resources :articles

  root :to => "articles#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    else
      can :read, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
	resourcify
	belongs_to :user

	validates_presence_of :title
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Registro guardado correctamente.' }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :desc, :other, :due_date, :start_date, :end_date, :status_id, :priority, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
	def article_status(status)
		case status
			when 1
				"<span class='label label-default'>Solicitado</span>".html_safe
			when 2
				"<span class='label label-primary'>Aprobado</span>".html_safe
			when 3
				"<span class='label label-danger'>No Aprobado</span>".html_safe
			when 4
				"<span class='label label-success'>Publicado</span>".html_safe
			else
				"N/A"
		end
	end

	def article_priority(priority)
		case priority
			when 1
				"<span class='badge alert-danger'>Alta</span>".html_safe
			when 2
				"<span class='badge alert-info'>Normal</span>".html_safe
			when 3
				"<span class='badge alert-default'>Baja</span>".html_safe
			else
				"N/A"
		end
	end
end

app/views/articles/_form.html.erb
<%= form_for @article, :html => {:class => 'form-horizontal', :role => "form" }  do |f|  %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %>, verifica por favor que los siguientes datos sean válidos:</h2>

      <ul>
        <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => "col-sm-2 control-label" %>
    <div class="col-xs-5 col-sm-4 col-md-4 col-lg-4">
      <%= f.text_field :title, :class => "form-control" %>
    </div>
  </div>

   <div class="form-group">
    <%= f.label :desc, :class => "col-sm-2 control-label" %>
    <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
      <%= f.text_area :desc, :class => "form-control", :rows => "4" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :other, :class => "col-sm-2 control-label" %>
    <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
      <%= f.text_area :other, :class => "form-control", :rows => "2" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :due_date, :class => "col-sm-2 control-label" %>
    <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
      <div class="checkbox">
        Sí <%= f.radio_button(:due_date, true) %> No <%= f.radio_button(:due_date, false) %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :start_date, :class => "col-sm-2 control-label" %>
    <div class="col-xs-5 col-sm-2 col-md-2 col-lg-2">
      <div class="input-group date">
        <%= f.text_field :start_date, :class => "form-control", "data-behaviour"=>'datepicker'  %>
        <span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
      </div>
    </div>

    <div class="form-group">
    <%= f.label :end_date, :class => "col-sm-2 control-label" %>
    <div class="col-xs-5 col-sm-2 col-md-2 col-lg-2">
      <div class="input-group date">
        <%= f.text_field :end_date, :class => "form-control", "data-behaviour"=>'datepicker'  %>
        <span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
      </div>
    </div>
  </div>
  </div>

  <div class="form-group">
    <%= f.label :status_id, :class => "col-sm-2 control-label" %>
    <div class="col-xs-5 col-sm-4 col-md-4 col-lg-4">
      <%= f.select :status_id, { "Solicitado" => "1", "Aprobado" => "2", "No aprobado" => "3", "Publicado" => "4"},{},{:class => "form-control"} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :priority, :class => "col-sm-2 control-label" %>
    <div class="col-xs-5 col-sm-4 col-md-4 col-lg-4">
       <%= f.select :priority, { "Alta" => "1", "Normal" => "2", "Baja" => "3"},{:selected => @article.priority.nil? ? "2" : @article.priority },{:class => "form-control"} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :requested_by, :class => "col-sm-2 control-label" %>
    <div class="col-xs-5 col-sm-4 col-md-4 col-lg-4">
      <%= f.text_field :requested_by, :class => "form-control"%>
    </div>
  </div>

    <%= f.hidden_field :user_id, :value => current_user.id %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "Guardar", :class => "btn btn-success btn-lg" %>
    </div>
  </div>



<% end %>

<script type="text/javascript">
  $(document).ready(function(){
    $('.input-group.date').datepicker({
      format: "dd/mm/yyyy",
      language: "es",
      autoclose: true
    });
  })
</script>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<legend><h3>Lista de publicaciones en Web Geología</h3></legend>

<table class="table table-condensed table-condensed table-bordered">
  <thead>
    <tr>
      <th>Título</th>
      <th>Contenido</th>
      <th>Estatus</th>
      <th>Prioridad</th>
      <th>Solicitado por</th>
      <th colspan="3">Opciones</th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.desc %></td>
        <td><%= article_status(article.status_id) %></td>
        <td><%= article_priority article.priority %></td>
        <td><%= article.requested_by %></td>
        <td><%= link_to 'Detalles', article, :class => "btn btn-info btn-sm" %></td>
        <td><%= link_to 'Modificar', edit_article_path(article), :class => "btn btn-warning btn-sm"   %></td>
        <td><%= link_to 'Eliminar', article, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Registrar solicitud de publicación', new_article_path, :class => "btn btn-primary btn-sm" %>

app/views/articles/new.html.erb
<div class="row clearfix">
	<div class="col-md-12 column">
		<legend><h4>Registro de solicitud de publicación de información en página web.</h4></legend>
		<%= render 'form' %>
	</div>
</div>

<%= link_to 'Regresar', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Titulo:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @article.desc %>
</p>

<p>
  <strong>Información adicional:</strong>
  <%= @article.other %>
</p>

<p>
  <strong>¿Tiene vigencia?:</strong>
  <%= !@article.due_date.nil? && @article.due_date == true ? "Sí" : "No" %>
</p>

<p>
  <strong>Inicio de la publicación:</strong>
  <%= l @article.start_date unless @article.start_date.nil?%>
</p>

<p>
  <strong>Fin de la publicación:</strong>
  <%= l @article.end_date unless @article.end_date.nil? %>
</p>

<p>
  <strong>Status:</strong>
  <%= article_status @article.status_id %>
</p>

<p>
  <strong>Priority:</strong>
  <%= article_priority @article.priority %>
</p>

<p>
  <strong>Solicitado por:</strong>
  <%= @article.requested_by %>
</p>

<%= link_to 'Modificar', edit_article_path(@article), :class => "btn btn-warning btn-sm" %> |
<%= link_to 'Regresar', articles_path, :class => "btn btn-info btn-sm" %>

app/views/home/index.html.erb
<h3>Home</h3>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Instituto de Geología - UNAM", root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links_left' %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links_right' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/_navigation_links_left.html.erb
<% if user_signed_in? %>
<li class="dropdown">
  <a id="main_menu" href="#" data-toggle="dropdown" class="dropdown-toggle">Publicaciones<span class="caret"></span></a>
  <ul class="dropdown-menu" aria-labelledby="main_menu">
    <li>
      <%= link_to "Lista de solicitudes", articles_path, :class => 'dropdown-toggle' %>
    </li>
    <li>
      <%= link_to "Nuevo registro de solicitud", new_article_path, :class => 'dropdown-toggle' %>
    </li>


  </ul>
</li>
<% end %>

app/views/layouts/_navigation_links_right.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
	<li class="dropdown">
    	<%= link_to(raw("Mi cuenta <span class='caret'></span>"),"#",{ :id => 'profile_menu', :class => 'dropdown-toggle', :data => {:toggle => "dropdown"}})  %>
		<ul class="dropdown-menu" aria-labelledby="profile_menu">
			<li> 
				<%= link_to "Modificar mi cuenta", edit_user_registration_path,{:class => 'dropdown-toggle'}  %> 
			</li>
			<li>
				<%= link_to "Salir", destroy_user_session_path, :method => :delete %>
			</li>
		</ul>
	</li>

  
<% else %>
  <li><%= link_to 'Ingresar', new_user_session_path %></li>
  <li><%link_to 'Registrarse', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><% link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Intranet" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Intranet" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <div class="container">
       <%= render 'layouts/messages' %>
       <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= collection_select :user, :role_ids, Role.all, :id, :name, checked: user.role_ids.first %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h3>Users</h3>
<div class="span8">
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Registered</th>
      <th>Role</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at.to_date %></td>
      <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
      <td>
        <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
        <%= render user %>
      </td>
      <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>
<%= link_to 'Edit account', edit_user_path %>